# springdoc-openapi项目配置
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: cn.graht.springbootinit.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
spring:
  redis:
    timeout: 3000
    lettuce:
      pool:
        max-active: 20
        min-idle: 4
        max-idle: 10
    host: 121.40.231.89
    port: 6379
    password: graht